export const SOCKET_CONFIG = {
  HEARTBEAT_INTERVAL: 30000,
  INITIAL_RECONNECT_DELAY: 1000,
  MAX_RECONNECT_DELAY: 10000,
  NORMAL_CLOSE_CODE: 1000,
  PING_PAYLOAD: 'ping',
  PONG_PAYLOAD: 'pong',
};
